name: Build And Push Docker Image

on:
  push:
    branches:
       - 'build'

  watch:
    types: started

jobs:
  build:
    runs-on: ubuntu-latest
    
    permissions:
      packages: write
      contents: read

    name: build
    env:
      IMAGE_NAME: bilibilitoolpro
    steps:
      - 
        name: Checkout
        uses: actions/checkout@master
      -
        name: Set time zone
        uses: szenius/set-timezone@v1.0
        with:
          timezoneLinux: "Asia/Shanghai"
          timezoneMacos: "Asia/Shanghai"
          timezoneWindows: "China Standard Time"  
      -        
        name: Set Up QEMU
        uses: docker/setup-qemu-action@v1
      - 
        name: Set Up Buildx
        uses: docker/setup-buildx-action@v1      
      - 
        name: Login DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}        
      - 
        name: Set Up Cache
        uses: actions/cache@v2
        id: buildx-cache
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx
      - 
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64,linux/arm/v7
        
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:latest
            
            
      - name: Sync Readme
        uses: ms-jpq/sync-dockerhub-readme@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
          repository: ${{ secrets.DOCKER_HUB_USERNAME }}/${{ env.IMAGE_NAME }}
          readme: "./Readme.md"

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}  
